---
pool:
  name: default
  vmImage: 'ubuntu-20.04'



trigger: 
   - master


extends:
  template: ./templates/maven_build.yml
  parameters: 
    branch: 'master'
    agentvmImage: 'ubuntu-20.04'
    jdkVersion: '1.17'