---
- name: install java 
  hosts: all
  become: yes
  tasks:
    - name: install java openjdk
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present

    