---
pool: 
  name: default
  vmImage: 'ubuntu-20.04'


trigger:
  - main


steps:
  - task: maven@3
    inputs: 
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      publishJUnitResults: true 
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkVersionOption: '/usr/lib/jvm/java-17-openjdk-amd64'
      
